name: Python pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: pytest ${{ matrix.python-version }}/${{ matrix.mediawiki-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]  # 3.11-dev
        mediawiki-version: [ '1.35.5-wmde.6', '1.36.3-wmde.5' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker containers with
        run: |
          docker-compose -f ./docker-compose.yml -f ./docker-compose.extra.yml up -d
        working-directory: test/docker-compose
        env:
          WIKIBASE_BUNDLE_IMAGE_NAME: ${{ matrix.mediawiki-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: wikibase/wikibase-bundle:${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Upgrade setup tools
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          python -m pip install .[dev]
      - name: Test with pytest
        run: |
          python -m pytest
